# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ca456d5ae83b33a0509f2d670d9616532e8091e587ba30ba916ad43232d249229966655ccc40d4c27372b329cf4ff3a9985192c70cd7585a3b3db52cbb1775

test:
  secret_key_base: b3f9f4a337ff0496bd8ba584a0b8cda77446bb83cac767de541016a7dea44428ff946bf491bb60707fa60722535f60881c07173aff99f042362d32abfa7a0005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
